### ISSUE TITLE
Investigate whether dynamic imports are still needed

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-test#204]
## Summary
A few months ago we had to start using `dynamic` imports in order for the components get rendered, or else the server would error out with this message:
![image](https://user-images.githubusercontent.com/24970122/156464778-a2e12e38-510e-4018-8a68-7d379e6bf942.png)

Not sure if this is still needed in our pages since we're able to use some regular imports properly, so we might need to investigate if it is so. 

How it's currently being done:

```
const DDSCardCTAFooter = dynamic(
  import(
    "@carbon/ibmdotcom-web-components/es/components-react/cta/card-cta-footer"
  ),
  { ssr: true }
);
```

How it should be (hopefully):
```
import DDSCardCTAFooter from '@carbon/ibmdotcom-web-components/es/components-react/cta/card-cta-footer';
```

**Comment by jeffchew** [comment]
@IgnacioBecerra is there a priority for this?

**Comment by IgnacioBecerra** [comment]
@jeffchew Everything is working properly at the moment with the dynamic imports so far, so this isn't critical
