### ISSUE TITLE
Solutions Page: Content Group Horizontal has the two content group mis-aligned

### ISSUE THREAD

**Issue by diegomarcuz** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-test#46]
## Detailed description

> Describe in detail the issue you're having.

On the Solution Page, Content Group Horizontal has the two content group mis-aligned

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Content Group Horizontal

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Second content group needs to behave as the first content

> What browser are you working in?

Google Chrome

> What version of the IBM.com Library are you using?

1.9.0-rc.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Solutions Page template

## Steps to reproduce the issue

1. Step one
- Go to: https://ibmdotcom-nextjs-staging.mybluemix.net/solutions.html
2. Step two
- Click on the Content Group Horizontal tab

## Additional information

![image](https://user-images.githubusercontent.com/37422384/88716576-a01c5e00-d0f5-11ea-9667-2a0e4b5482a3.png)

**Comment by RobertaJHahn** [comment]
@jeffchew This issue is very old.  Gui thinks this issue can be closed.  What do you think?  Close?

**Comment by RobertaJHahn** [comment]
@Praveen-sr Jeff would like this tested to see whether the bug still exists before closing.

**Comment by Praveen-sr** [comment]
@RobertaJHahn I re tested this on [Solution page](https://ibmdotcom-nextjs-staging.mybluemix.net/solutions.html), still the content group links are mis-aligned. 

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/4ce3cf11-0eba-4f2f-a6cc-cd9c9a20773c)

**Comment by IgnacioBecerra** [comment]
@Praveen-sr Would you be able to retest this? Using the[ link](https://ibmdotcom-nextjs-staging.mybluemix.net/solutions.html) you provided, it appears this has been fixed. 

cc: @RobertaJHahn

**Comment by Praveen-sr** [comment]
@IgnacioBecerra Re tested this on the above link, working fine

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/91e9d113-0f61-4196-83e8-6fffdff2943c)
