### ISSUE TITLE
Learn Page: 2 copy texts are spanning out the page

### ISSUE THREAD

**Issue by diegomarcuz** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-test#47]
## Detailed description

> Describe in detail the issue you're having.

Learn Page: on the content block segmented 2 copy texts are spanning out the page

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Content Block Segmented

> What did you expect to happen? What happened instead? What would you like to
> see changed?

They don't span out of the page

> What browser are you working in?

Google Chrome

> What version of the IBM.com Library are you using?

1.9.0-rc.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Services Page

## Steps to reproduce the issue

1. Step one
- Go to: https://ibmdotcom-nextjs-staging.mybluemix.net/services.html
2. Step two
- Scroll down a little and see the issue happening as the image below

## Additional information

![image](https://user-images.githubusercontent.com/37422384/88718763-a2cc8280-d0f8-11ea-9072-7c6c98b4b48c.png)

**Comment by guilhermelMoraes** [comment]
@jeffchew I'm not sure what should I do with this one. Does it still need a fix or it's stale at this point?

**Comment by RobertaJHahn** [comment]
@Praveen-sr Jeff would like this tested to see whether the bug still exists before closing.

**Comment by Praveen-sr** [comment]
@RobertaJHahn I re tested this on [Learn page](https://ibmdotcom-nextjs-staging.mybluemix.net/learn.html), still the 2 copy texts are spanning out the page.

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/9aae4224-b764-4f38-8286-1e5646ddc161)

**Comment by kennylam** [comment]
@RobertaJHahn @Praveen-sr This has been fixed in the PR above.
