### ISSUE TITLE
Add possibility to use next/link instead of carbon/link

### ISSUE THREAD

**Issue by jannicz** [carbon-design-system/carbon-for-ibm-dotcom-nextjs-test#64]
### The problem
A lot of Carbon components make use of the internal Carbon [Link.js](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Link/Link.js) component. When using Next.js, you have to use [next/link](https://nextjs.org/docs/api-reference/next/link) as it provides features like prefetching and client side routing. Not using it would cause a page reload on each click (of a link). So far Next.js ist not compatible with the Carbon React Components without forking and exchanging the Link Component manually.

### The solution
I would wish a possibility (or example) to use the next/link instead of the carbon link, so that all features of Next.js can be fully used. Alternatively I could imagine a solution, where I would tell Carbon to only override the Link component with my own implementation (what is also not possible because of the imports).

### Additional information
 - There are similar problems/solutions in competing UI Libraries, i.e. Material supports a thing called **forwardRef**, where the native next/Link can pass its href attribute down to a Material child component ([here](https://dev.to/ivandotv/using-next-js-link-component-with-material-ui-buttons-and-menu-items-3m6a))
 - I know this is not easy to solve, but as Next.js gains more an more traction, it might become a larger problem in the future
 - I used Carbon Components React 7.21.0, Next.js 9.5 and Chrome browser

Thank you for this great Design System

**Comment by jeffchew** [comment]
Hi @jannicz, thank you for your reported issue and glad to see you're finding value in the NextJS implementation!

I believe you can go ahead and use the `next/link`, then apply the `bx--link` class to it to get the correct Carbon styling for it. The direct class itself can be pulled in from `carbon-components/scss/components/link/link` into your styles.

Let me know if this helps, or if there was something else that you were looking for with the Carbon `Link` that isn't captured there?

cc: @kennylam @RaphaelAmadeu

**Comment by jannicz** [comment]
Hi @jeffchew,

yes, this actually helps a lot. But I was also looking for a possibility to do the same with Links that are a child of another component, i.e. [Sidenav](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/UIShell/SideNavLink.js#L37). But I realize that this issue is actually a downside of Next as a library. So you can consider to closed!

**Comment by asudoh** [comment]
Sounds that the requirement is an ability to replace usage of `<Link>` component in Carbon core components. For that, one thing I can think of is dependency injection (e.g. https://webpack.js.org/plugins/normal-module-replacement-plugin/). Not sure if it works with Next, though.

**Comment by jannicz** [comment]
@asudoh, thank you for the hint. I will try to solve it that way. I am closing the issue.
